export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,scss}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#2f4025",
        "surface-container-low": "#f7f3ea",
        "surface-container-high": "#ece8df",
        "on-primary-fixed-variant": "#e5e2e1",
        "inverse-primary": "#c8c6c5",
        "secondary": "#695d46",
        "primary": "#000000",
        "on-secondary-fixed": "#231a08",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#d4e9c3",
        "primary-fixed": "#5f5e5e",
        "on-primary-fixed": "#ffffff",
        "surface-dim": "#dddad1",
        "on-tertiary-container": "#ffffff",
        "on-primary": "#e5e2e1",
        "on-tertiary-fixed": "#ffffff",
        "on-error-container": "#410002",
        "on-background": "#1c1c17",
        "primary-fixed-dim": "#474746",
        "outline-variant": "#c6c6c6",
        "inverse-surface": "#31312b",
        "secondary-fixed-dim": "#b9a98e",
        "outline": "#777777",
        "surface-container": "#f1eee5",
        "on-secondary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "on-surface-variant": "#474747",
        "error": "#ba1a1a",
        "surface-container-highest": "#e6e2d9",
        "on-error": "#ffffff",
        "secondary-fixed": "#d5c5a8",
        "secondary-container": "#e3d2b5",
        "tertiary-fixed-dim": "#3a4c30",
        "surface": "#fdf9f0",
        "background": "#fdf9f0",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#d4e9c3",
        "inverse-on-surface": "#f4f0e7",
        "surface-bright": "#fdf9f0",
        "on-secondary-container": "#231a08",
        "primary-container": "#3c3b3b",
        "on-surface": "#1c1c17",
        "surface-variant": "#e6e2d9",
        "error-container": "#ffdad6",
        "tertiary-container": "#677a5b",
        "on-secondary-fixed-variant": "#453a25",
        "tertiary-fixed": "#516446"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Work Sans", "sans-serif"],
        "label": ["Work Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
      skew: {
        '1': '1deg',
        '2': '2deg',
      }
    },
  },
  plugins: [],
}